apiVersion: v1
name: amazon-ec2-metadata-mock
description: A Helm chart for the Amazon EC2 Metadata Mock
version: 0.5.8
appVersion: v1.0.1
home: https://github.com/aws/amazon-ec2-metadata-mock
icon: https://raw.githubusercontent.com/aws/amazon-ec2-metadata-mock/master/helm/aws-logo.png
sources:
  - https://github.com/aws/amazon-ec2-metadata-mock
maintainers:
  - name: pdk27
    url: https://github.com/pdk27
    email: pdk27@users.noreply.github.com
  - name: brycahta
    url: https://github.com/brycahta
    email: brycahta@users.noreply.github.com
keywords:
  - ec2
  - aws-ec2
  - imds
  - ec2-instance-metadata
  - ec2-instance-metadata-mock
  - spot-interruption-mock
